# Generated by Django 6.0.3 on 2026-03-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('attendance_rate', models.FloatField()),
                ('study_hours', models.FloatField()),
                ('online_courses', models.FloatField()),
                ('assignment_rate', models.FloatField()),
                ('learning_style', models.CharField(max_length=50)),
                ('is_at_risk', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
